name: Update README with Uptime

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 12:00:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write  # Allows GitHub Actions to push updates

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use Personal Access Token

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run uptime script
        run: node update-readme.js

      - name: Commit and push if changed
        run: |
          git config --global user.name "ShoreNexx"  # GitHub username
          git config --global user.email "186189496+ShoreNexx@users.noreply.github.com"  # GitHub-provided noreply email
          git add README.md
          git diff --exit-code || (git commit -m "Updated uptime in README" && git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/YOUR_USERNAME/YOUR_REPO.git main)
